array_layout = "Block"
chain_indent = "Block"
chain_split_single_child = true
closure_block_indent_threshhold = 1
condense_wildcard_suffixes = true
control_style = "Rfc"
control_brace_style = "AlwaysSameLine"
fn_args_density = "Tall"
fn_args_layout = "Block"
fn_args_paren_newline = false
fn_brace_style = "SameLineWhere"
fn_call_style = "Block"
fn_empty_single_line = true
fn_return_indent = "WithWhereClause"
fn_single_line = true
format_strings = false
generics_indent = "Block"
hard_tabs = true
impl_empty_single_line = true
indent_match_arms = true
imports_indent = "Block"
import_layout = "HorizontalVertical"
item_brace_style = "SameLineWhere"
max_width = 80
newline_style = "Unix"
normalize_comments = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
single_line_if_else_max_width = 60
space_after_bound_colon = true
space_after_struct_lit_field_colon = true
space_after_type_annotation_colon = true
space_before_bound = false
space_before_struct_lit_field_colon = false
space_before_type_annotation = false
spaces_around_ranges = false
spaces_within_angle_brackets = false
spaces_within_parens = false
spaces_within_square_brackets = false
struct_field_align_threshold = 0
struct_lit_multiline_style = "PreferSingle"
struct_lit_single_line = true
struct_lit_style = "Block"
struct_lit_width = 70
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_try_shorthand = true
where_density = "CompressedIfEmpty"
where_layout = "HorizontalVertical"
where_pred_indent = "Block"
wrap_comments = true
wrap_match_arms = true
write_mode = "Diff"
